import type { Metadata } from "next";
import { Tomorrow } from "next/font/google";
import "./globals.css";


const tomorrow = Tomorrow({
  variable: "--font-tomorrow",
  weight: ['400', '700'],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tomorrow.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
