import type { Metadata } from "next";
import { Tomorrow } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";

const tomorrow = Tomorrow({
  variable: "--font-tomorrow",
  weight: ['400', '700'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tomorrow.variable} antialiased`}
      >
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
