// Mock data for credentials
export const mockCredentials = [
    {
      id: "1",
      name: "AWS Certified Solutions Architect",
      issuer: "Amazon Web Services",
      issueDate: "2023-05-15",
      expiryDate: "2026-05-15",
      description:
        "The AWS Certified Solutions Architect - Associate examination is intended for individuals who perform a solutions architect role. This exam validates an examinee's ability to effectively demonstrate knowledge of how to architect and deploy secure and robust applications on AWS technologies.",
      credentialUrl: "https://aws.amazon.com/certification/certified-solutions-architect-associate/",
      featured: true,
      tags: ["Cloud", "AWS", "Architecture"],
      skills: ["AWS", "Cloud Architecture", "Security", "Networking", "Storage"],
    },
    {
      id: "2",
      name: "React Developer Certification",
      issuer: "Meta",
      issueDate: "2023-02-10",
      expiryDate: null,
      description:
        "This certification validates your ability to create React applications, implement component-based architecture, and utilize React's core features including hooks, state management, and routing.",
      credentialUrl: "https://www.meta.com/certifications/",
      featured: false,
      tags: ["Frontend", "React", "JavaScript"],
      skills: ["React", "JavaScript", "Redux", "CSS", "HTML"],
    },
    {
      id: "3",
      name: "Google Cloud Professional",
      issuer: "Google Cloud",
      issueDate: "2022-11-20",
      expiryDate: "2025-11-20",
      description:
        "The Google Cloud Professional certification demonstrates your expertise in designing, developing, managing, and administering application infrastructure and data solutions on Google Cloud.",
      credentialUrl: "https://cloud.google.com/certification",
      featured: true,
      tags: ["Cloud", "Google", "Infrastructure"],
      skills: ["Google Cloud", "Kubernetes", "Cloud Storage", "BigQuery", "Cloud Functions"],
    },
    {
      id: "4",
      name: "Certified Kubernetes Administrator",
      issuer: "Cloud Native Computing Foundation",
      issueDate: "2023-01-05",
      expiryDate: "2026-01-05",
      description:
        "The Certified Kubernetes Administrator (CKA) program ensures that you have the skills, knowledge, and competency to perform the responsibilities of Kubernetes administrators.",
      credentialUrl: "https://www.cncf.io/certification/cka/",
      featured: false,
      tags: ["Kubernetes", "DevOps", "Container"],
      skills: ["Kubernetes", "Docker", "Container Orchestration", "Linux", "Networking"],
    },
    {
      id: "5",
      name: "Microsoft Azure Fundamentals",
      issuer: "Microsoft",
      issueDate: "2022-09-12",
      expiryDate: null,
      description:
        "Microsoft Azure Fundamentals validates your basic knowledge of cloud services and how those services are provided with Microsoft Azure.",
      credentialUrl: "https://learn.microsoft.com/en-us/certifications/azure-fundamentals/",
      featured: false,
      tags: ["Cloud", "Azure", "Microsoft"],
      skills: ["Azure", "Cloud Computing", "IaaS", "PaaS", "SaaS"],
    },
    {
      id: "6",
      name: "Certified Ethical Hacker",
      issuer: "EC-Council",
      issueDate: "2023-03-28",
      expiryDate: "2026-03-28",
      description:
        "The CEH credential certifies individuals in the specific network security discipline of Ethical Hacking from a vendor-neutral perspective.",
      credentialUrl: "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
      featured: false,
      tags: ["Security", "Ethical Hacking", "Cybersecurity"],
      skills: ["Penetration Testing", "Network Security", "Vulnerability Assessment", "Risk Management"],
    },
    {
      id: "7",
      name: "Data Science Professional",
      issuer: "IBM",
      issueDate: "2023-06-02",
      expiryDate: null,
      description:
        "This certification demonstrates your proficiency in data science, including open source tools, methodologies, Python, databases, SQL, data visualization, data analysis, and machine learning.",
      credentialUrl: "https://www.ibm.com/training/certification/C0001",
      featured: true,
      tags: ["Data Science", "Machine Learning", "Python"],
      skills: ["Python", "Machine Learning", "Data Analysis", "Statistics", "Data Visualization"],
    },
    {
      id: "8",
      name: "Certified Scrum Master",
      issuer: "Scrum Alliance",
      issueDate: "2022-08-15",
      expiryDate: "2024-08-15",
      description:
        "As a Certified ScrumMaster® (CSM®), you'll help the Scrum Team perform at their highest level. CSMs also protect the team from both internal and external distractions.",
      credentialUrl: "https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster",
      featured: false,
      tags: ["Agile", "Scrum", "Project Management"],
      skills: ["Scrum", "Agile Methodologies", "Team Facilitation", "Project Management"],
    },
    {
      id: "9",
      name: "Cybersecurity Fundamentals",
      issuer: "CompTIA",
      issueDate: "2023-04-10",
      expiryDate: "2026-04-10",
      description:
        "CompTIA Security+ is a global certification that validates the baseline skills necessary to perform core security functions and pursue an IT security career.",
      credentialUrl: "https://www.comptia.org/certifications/security",
      featured: false,
      tags: ["Security", "CompTIA", "Cybersecurity"],
      skills: ["Network Security", "Compliance", "Identity Management", "Access Control", "Cryptography"],
    },
    {
      id: "10",
      name: "Full Stack Web Developer",
      issuer: "Udacity",
      issueDate: "2022-12-05",
      expiryDate: null,
      description:
        "This nanodegree program teaches the fundamentals of full-stack web development, including frontend frameworks, backend APIs, and database integration.",
      credentialUrl: "https://www.udacity.com/course/full-stack-web-developer-nanodegree--nd0044",
      featured: false,
      tags: ["Web Development", "Full Stack", "JavaScript"],
      skills: ["JavaScript", "Node.js", "React", "SQL", "API Development"],
    },
    {
      id: "11",
      name: "TensorFlow Developer",
      issuer: "Google",
      issueDate: "2023-07-20",
      expiryDate: null,
      description:
        "The TensorFlow Developer Certificate program validates your skills in using TensorFlow to solve deep learning and ML problems.",
      credentialUrl: "https://www.tensorflow.org/certificate",
      featured: false,
      tags: ["Machine Learning", "TensorFlow", "AI"],
      skills: ["TensorFlow", "Deep Learning", "Neural Networks", "Computer Vision", "NLP"],
    },
    {
      id: "12",
      name: "Oracle Certified Java Programmer",
      issuer: "Oracle",
      issueDate: "2022-10-18",
      expiryDate: null,
      description:
        "The Java SE 11 Programmer certification helps you build your credentials and get recognized for your expertise in Java technology.",
      credentialUrl: "https://education.oracle.com/java-se-11-programmer-i/pexam_1Z0-815",
      featured: false,
      tags: ["Java", "Programming", "Oracle"],
      skills: ["Java", "Object-Oriented Programming", "API Development", "Debugging"],
    },
  ]
  
  